---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: DcimDevice
  data:
    - name: "spine-infrahub-dc1-1"
      status: provisioning
      serial: "INFRAHUB001"
    - name: "spine-infrahub-dc1-2"
      status: provisioning
      serial: "INFRAHUB002"
    - name: "leaf-infrahub-dc1-1-1"
      status: provisioning
      serial: "INFRAHUB003"
    - name: "leaf-infrahub-dc1-1-2"
      status: provisioning
      serial: "INFRAHUB004"
    - name: "leaf-infrahub-dc1-2-1"
      status: provisioning
      serial: "INFRAHUB005"
    - name: "leaf-infrahub-dc1-2-2"
      status: provisioning
      serial: "INFRAHUB006"
    - name: "spine-infrahub-dc2-1"
      status: provisioning
      serial: "INFRAHUB011"
    - name: "spine-infrahub-dc2-2"
      status: provisioning
      serial: "INFRAHUB012"
    - name: "leaf-infrahub-dc2-1-1"
      status: provisioning
      serial: "INFRAHUB013"
    - name: "leaf-infrahub-dc2-1-2"
      status: provisioning
      serial: "INFRAHUB014"
    - name: "leaf-infrahub-dc2-2-1"
      status: provisioning
      serial: "INFRAHUB015"
    - name: "leaf-infrahub-dc2-2-2"
      status: provisioning
      serial: "INFRAHUB016"
