---
# =============================================================================
# Underlay/Overlay
# =============================================================================
underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp
p2p_uplinks_mtu: 1500

bgp_graceful_restart:
  enabled: true

# =============================================================================
# EVPN Multi-Domain Gateway — DCI peering between DC1 and DC2 border leaves
# =============================================================================
evpn_ebgp_gateway_multihop: 3

# =============================================================================
# EVPN convergence
# =============================================================================
custom_structured_configuration_router_bgp:
  address_family_evpn:
    route:
      import_ethernet_segment_ip_mass_withdraw: true
      export_ethernet_segment_ip_mass_withdraw: true
    layer_2_fec_in_place_update:
      enabled: true

# =============================================================================
# Interfaces (cEOS defaults)
# =============================================================================
default_interfaces:
  - types: [spine]
    platforms: [default]
    downlink_interfaces: [Ethernet1-4/1]
  - types: [l3leaf]
    platforms: [default]
    uplink_interfaces: [Ethernet49-50/1]

# =============================================================================
# Platform settings — cEOS
# =============================================================================
custom_platform_settings:
  - platforms: [cEOSLab]
    feature_support:
      bgp_update_wait_for_convergence: false
      bgp_update_wait_install: false
      interface_storm_control: false
      queue_monitor_length_notify: false
      sflow_subinterfaces: false
      evpn_gateway_all_active_multihoming: true
    management_interface: Management1
    raw_eos_cli: |
      platform tfa
        interface mode relaying
