---
- name: "changes/major"
  description: "Bump major version (breaking change)"
  color: "b60205"

- name: "changes/minor"
  description: "Bump minor version (new feature)"
  color: "ff9f1c"

- name: "changes/patch"
  description: "Bump patch version (bug fix)"
  color: "cfda2c"

- name: "ci/skip-changelog"
  description: "No news fragment required for this pull request"
  color: "dddddd"
