---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: CoreGeneratorAction
  data:
    - name: run-pod-generator
      generator: generate-pod
    - name: run-rack-generator
      generator: generate-rack
    - name: run-avd-device-structured-config-generator
      generator: generate-avd-device-structured-config
    - name: run-backfill-structured-config-generator
      generator: backfill-structured-config
    - name: run-server-cabling-generator
      generator: generate-server-cabling

---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: CoreNodeTriggerRule
  data:

    - name: trigger-pod-generator-update-checksum
      branch_scope: "other_branches"
      node_kind: NetworkPod
      mutation_action: "updated"
      action: run-pod-generator
      matches:
        kind: CoreNodeTriggerAttributeMatch
        data:
          - attribute_name: checksum
            value_match: any

    - name: trigger-pod-generator-update-index
      branch_scope: "other_branches"
      node_kind: NetworkPod
      mutation_action: "updated"
      action: run-pod-generator
      matches:
        kind: CoreNodeTriggerAttributeMatch
        data:
          - attribute_name: index
            value_match: any

    - name: trigger-pod-generator-update-amount-of-spines
      branch_scope: "other_branches"
      node_kind: NetworkPod
      mutation_action: "updated"
      action: run-pod-generator
      matches:
        kind: CoreNodeTriggerAttributeMatch
        data:
          - attribute_name: amount_of_spines
            value_match: any

    - name: trigger-pod-generator-update-role
      branch_scope: "other_branches"
      node_kind: NetworkPod
      mutation_action: "updated"
      action: run-pod-generator
      matches:
        kind: CoreNodeTriggerAttributeMatch
        data:
          - attribute_name: role
            value_match: any

    - name: trigger-rack-generator-update-checksum
      branch_scope: "other_branches"
      node_kind: LocationRack
      mutation_action: "updated"
      action: run-rack-generator
      matches:
        kind: CoreNodeTriggerAttributeMatch
        data:
          - attribute_name: checksum
            value_match: any

    - name: trigger-rack-generator-update-index
      branch_scope: "other_branches"
      node_kind: LocationRack
      mutation_action: "updated"
      action: run-rack-generator
      matches:
        kind: CoreNodeTriggerAttributeMatch
        data:
          - attribute_name: index
            value_match: any

    - name: trigger-rack-generator-update-rack-type
      branch_scope: "other_branches"
      node_kind: LocationRack
      mutation_action: "updated"
      action: run-rack-generator
      matches:
        kind: CoreNodeTriggerAttributeMatch
        data:
          - attribute_name: rack_type
            value_match: any

    - name: trigger-avd-structured-config-generator-update-avd-hostvars-ready
      branch_scope: "other_branches"
      node_kind: NetworkFabric
      mutation_action: "updated"
      action: run-avd-device-structured-config-generator
      matches:
        kind: CoreNodeTriggerAttributeMatch
        data:
          - attribute_name: avd_hostvars_ready
            value: "True"
            value_previous: "False"

    - name: trigger-backfill-structured-config-update-checksum
      branch_scope: "other_branches"
      node_kind: AvdStructuredConfigFile
      mutation_action: "updated"
      action: run-backfill-structured-config-generator
      matches:
        kind: CoreNodeTriggerAttributeMatch
        data:
          - attribute_name: checksum
            value_match: any

    - name: trigger-backfill-structured-config-created
      branch_scope: "other_branches"
      node_kind: AvdStructuredConfigFile
      mutation_action: "created"
      action: run-backfill-structured-config-generator

    - name: trigger-server-cabling-generator-created
      branch_scope: "other_branches"
      node_kind: ComputePhysicalServer
      mutation_action: "created"
      action: run-server-cabling-generator
