---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: CoreAccountGroup
  data:
    - name: AVD
---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: CoreStandardGroup
  data:
    - name: halls
    - name: racks
    - name: fabrics
    - name: pods
    - name: avd_devices
    - name: servers
    - name: avd_artifacts
    - name: avd_structured_configs
