---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: DcimPlatform
  data:
    - name: EOS
      manufacturer: Arista
      description: Arista EOS
      ansible_network_os: arista.eos.eos
      containerlab_os: arista_ceos
---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: DcimDeviceType
  data:
    - name: "PowerSwitch Z9864F-ON"
      manufacturer: ["Dell"]
    - name: "PowerSwitch S5232F-ON"
      manufacturer: ["Dell"]
    - name: "Arista 7050CX3-32C"
      manufacturer: Arista
      platform: EOS
      description: "Arista 7050X3C, 32x100GbE QSFP+ & 2xSFP+ switch"
      part_number: DCS-7050CX3-32C
      height: 1
      full_depth: true
      weight: 9
    - name: "Arista 7050SX3-48YC8C"
      manufacturer: Arista
      platform: EOS
      description: "Arista 7050X3, 48x25GbE SFP & 8x100GbE QSFP switch"
      part_number: DCS-7050SX3-48YC8C
      height: 1
      full_depth: true
      weight: 9
