---
# DNS Servers
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: NetworkDnsServer
  data:
    - name: dns-primary
      ip_address: 192.168.1.1/32
      vrf: MGMT
    - name: dns-secondary
      ip_address: 8.8.8.8/32
---
# NTP Servers
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: NetworkNtpServer
  data:
    - name: 0.pool.ntp.org
      server_vrf: use_mgmt_interface_vrf
    - name: 1.pool.ntp.org
      server_vrf: use_mgmt_interface_vrf
---
# Local Users
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: NetworkLocalUser
  data:
    - name: arista
      privilege: 15
      role: network-admin
      password_type: sha512
      password: "$6$arista$abc123examplehashreplacewithreal"
    - name: admin
      privilege: 15
      role: network-admin
      password_type: sha512
      password: "$6$admin$abc123examplehashreplacewithreal"
