---
# DNS Servers
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: NetworkDnsServer
  data:
    - name: dns-google
      ip_address: 8.8.8.8/32
---
# NTP Servers
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: NetworkNtpServer
  data:
    - name: time.google.com
---
# Local Users
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: NetworkLocalUser
  data:
    - name: admin-nopass
      privilege: 15
      role: network-admin
      password_type: type7
      password: "nopassword"
    - name: mtache-nopass
      privilege: 15
      role: network-admin
      password_type: type7
      password: "nopassword"
