---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: TemplateDcimDevice
  parameters:
    expand_range: true
  data:
    - template_name: "arista-7050cx3-32c-spine-switch"
      device_type: ["Arista", "Arista 7050CX3-32C"]
      role: "spine"
      interfaces:
        kind: TemplateInterfaceVirtual
        data:
          - template_name: "Arista7050CX3SpineLoopback0"
            name: "Loopback0"
            role: "loopback"
    - template_name: "arista-7050cx3-32c-spine-switch"
      device_type: ["Arista", "Arista 7050CX3-32C"]
      role: "spine"
      interfaces:
        kind: TemplateInterfacePhysical
        parameters:
          expand_range: true
        data:
          - template_name: "Arista7050CX3SpineEthernet[1-32]/1"
            name: "Ethernet[1-32]/1"
            profiles: ["profile-interface-leaf"]

    - template_name: "arista-7050sx3-48yc8c-leaf-switch"
      device_type: ["Arista", "Arista 7050SX3-48YC8C"]
      role: "leaf"
      interfaces:
        kind: TemplateInterfaceVirtual
        data:
          - template_name: "Arista7050SX3LeafLoopback0"
            name: "Loopback0"
            role: "loopback"
    - template_name: "arista-7050sx3-48yc8c-leaf-switch"
      device_type: ["Arista", "Arista 7050SX3-48YC8C"]
      role: "leaf"
      interfaces:
        kind: TemplateInterfacePhysical
        parameters:
          expand_range: true
        data:
          - template_name: "Arista7050SX3LeafEthernet[1-48]"
            name: "Ethernet[1-48]"
            profiles: ["profile-interface-server"]
          - template_name: "Arista7050SX3LeafEthernet[49-50]/1"
            name: "Ethernet[49-50]/1"
            profiles: ["profile-interface-spine"]
