---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: ProfileDcimInterface
  data:
    - profile_name: "profile-server-compute"
      role: "server"
      mtu: 9000
      tagged_vlan: 
        - ["Servers"]
        - ["Storage"]
    - profile_name: "profile-server-gpu"
      role: "server"
      mtu: 9000
      tagged_vlan: 
        - ["Servers"]
        - ["Storage"]
        - ["Backup"]
