query GenerateAvdDeviceInputsQuery($hostname: String!) {
  NetworkDevice(hostname__value: $hostname) {
    edges {
      node {
        __typename
        id
        hostname {
          value
        }
        role {
          value
        }
        bgp_asn {
          value
        }
        node_id {
          value
        }
        loopback_ip {
          node {
            __typename
            id
            address {
              value
            }
          }
        }
        mgmt_ip {
          node {
            __typename
            id
            address {
              value
            }
          }
        }
        pod {
          node {
            id
            name {
              value
            }
            parent {
              node {
                __typename
                id
                name {
                  value
                }
                ... on NetworkFabric {
                  mgmt_gateway {
                    value
                  }
                  mgmt_routes1 {
                    value
                  }
                  avd_evpn {
                    node {
                      __typename
                      ebgp_multihop {
                        value
                      }
                      overlay_bgp_rtc {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
        interfaces {
          edges {
            node {
              __typename
              id
              name {
                value
              }
              role {
                value
              }
              tagged_vlan {
                edges {
                  node {
                    __typename
                    vlan_id {
                      value
                    }
                    status {
                      value
                    }
                  }
                }
              }
              untagged_vlan {
                node {
                  __typename
                  vlan_id {
                    value
                  }
                  status {
                    value
                  }
                }
              }
              link {
                node {
                  __typename
                  id
                  endpoints {
                    edges {
                      node {
                        __typename
                        id
                        ... on NetworkInterface {
                          name {
                            value
                          }
                          device {
                            node {
                              __typename
                              id
                              hostname {
                                value
                              }
                              ... on NetworkDevice {
                                role {
                                  value
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
