query GenerateAvdDeviceInputsQuery($hostname: String!) {
  NetworkDevice(hostname__value: $hostname) {
    edges {
      node {
        id
        hostname {
          value
        }
        role {
          value
        }
        bgp_asn {
          value
        }
        node_id {
          value
        }
        loopback_ip {
          node {
            id
            address {
              value
            }
          }
        }
        mgmt_ip {
          node {
            id
            address {
              value
            }
          }
        }
        pod {
          node {
            id
            name {
              value
            }
            parent {
              node {
                id
                name {
                  value
                }
                ... on NetworkFabric {
                  mgmt_gateway {
                    value
                  }
                  mgmt_routes1 {
                    value 
                  }
                  avd_evpn {
                    node {
                      ebgp_multihop {
                        value
                      }
                      overlay_bgp_rtc {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
        interfaces {
          edges {
            node {
              id
              name {
                value
              }
              role {
                value
              }
              link {
                node {
                  id
                  endpoints {
                    edges {
                      node {
                        id
                        ... on NetworkInterface {
                          name {
                            value
                          }
                          device {
                            node {
                              id
                              hostname {
                                value
                              }
                              role {
                                value
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}