query BackfillStructuredConfigQuery($device_hostname: String!) {
  AvdArtifact(device__hostname__value: $device_hostname) {
    edges {
      node {
        id
        structured_config_identifier {
          value
        }
        device {
          node {
            __typename
            id
            ... on NetworkDevice {
              hostname {
                value
              }
              role {
                value
              }
              interfaces {
                edges {
                  node {
                    id
                    name {
                      value
                    }
                    role {
                      value
                    }
                    mtu {
                      value
                    }
                    ip_address {
                      node {
                        id
                        address {
                          value
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
