query GenerateAvdInputsQuery($fabric_name: String!) {
  NetworkFabric(name__value: $fabric_name) {
    edges {
      node {
        __typename
        id
        name {
          value
        }
        children {
          edges {
            node {
              __typename
              ... on NetworkPod {
                __typename
                racks {
                  edges {
                    node {
                      __typename
                      devices {
                        edges {
                          node {
                            __typename
                            id
                            name {
                              value
                            }
                            avd_artifact {
                              node {
                                __typename
                                hostvar_identifier {
                                  value
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
                devices {
                  edges {
                    node {
                      __typename
                      id
                      name {
                        value
                      }
                      avd_artifact {
                        node {
                          __typename
                          hostvar_identifier {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
