query GenerateAvdInputsQuery($fabric_name: String!) {
  NetworkFabric(name__value: $fabric_name) {
    edges {
      node {
        id
        name {
          value
        }
        children {
          edges {
            node {
              ... on NetworkPod {
                racks {
                  edges {
                    node {
                      devices {
                        edges {
                          node {
                            id
                            hostname {
                              value
                            }
                            avd_artifact {
                              node {
                                hostvar_identifier {
                                  value
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
                devices {
                  edges {
                    node {
                      id
                      hostname {
                        value
                      }
                      avd_artifact {
                        node {
                          hostvar_identifier {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
