query ServerCablingQuery($name: String!) {
  ComputePhysicalServer(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        role {
          value
        }
        status {
          value
        }
        rack {
          node {
            id
            name {
              value
            }
          }
        }
        interfaces {
          edges {
            node {
              id
              name {
                value
              }
              role {
                value
              }
              status {
                value
              }
              ... on DcimEndpoint {
                connector {
                  node {
                    id
                  }
                }
              }
              tagged_vlan {
                edges {
                  node {
                    id
                    name {
                      value
                    }
                  }
                }
              }
              untagged_vlan {
                node {
                  id
                  name {
                    value
                  }
                }
              }
              profiles {
                edges {
                  node {
                    id
                    ... on ProfileDcimInterface {
                      profile_name {
                        value
                      }
                      tagged_vlan {
                        edges {
                          node {
                            id
                            name {
                              value
                            }
                          }
                        }
                      }
                      untagged_vlan {
                        node {
                          id
                          name {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
