query RackGeneratorQuery($name: String!) {
  LocationRack(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        checksum {
          value
        }
				index {
					value
				}
				rack_type {
					value
				}
				amount_of_leafs {
					value
				}
				mlag {
					value
				}
				leaf_switch_template {
					node {
						__typename
						id
					}
				}
				amount_of_l2leafs {
					value
				}
				l2leaf_switch_template {
					node {
						__typename
						id
					}
				}
				parent {
					node {
						__typename
						id
						name {
							value
						}
					}
				}
				pod {
					node {
						id
						name {
							value
						}
						index {
							value
						}
						prefix_pool {
							node {
								__typename
								id
							}
						}
						loopback_pool {
							node {
								__typename
								id
							}
						}
						amount_of_spines {
							value
						}
						leaf_interface_sorting_method {
							value
						}
						spine_interface_sorting_method {
							value
						}
						parent {
							node {
								__typename
								... on NetworkFabric {
									underlay_routing_protocol {
										value
									}
									asn_pool {
										node {
											id
										}
									}
									node_id_pool {
										node {
											id
										}
									}
									mgmt_pool {
										node {
											id
										}
									}
								}
							}
						}
					}
				}
      }
    }
  }
}
