query FabricGeneratorQuery($name: String!) {
  NetworkFabric(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        amount_of_super_spines {
          value
        }
        underlay_routing_protocol {
          value
        }
        super_spine_switch_template {
          node {
            __typename
            id
          }
        }
        mgmt_gateway {
          value
        }
        asn_pool {
          node {
            id
          }
        }
        node_id_pool {
          node {
            id
          }
        }
        mgmt_pool {
          node {
            id
          }
        }
        vtep_pool {
          node {
            id
            resources {
              edges {
                node {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
