query SubmitCVWorkspace($name: String!) {
  NetworkFabric(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
      }
    }
  }
  CloudvisionWorkspace(status__value: "built") {
    edges {
      node {
        id
        workspace_id {
          value
        }
        proposed_change_id {
          value
        }
        name {
          value
        }
        status {
          value
        }
        fabric {
          node {
            id
            name {
              value
            }
          }
        }
      }
    }
  }
}
