query AvdFabricDevicesQuery($name: String!) {
  NetworkFabric(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
      }
    }
  }
  NetworkDevice {
    edges {
      node {
        id
        hostname {
          value
        }
        pod {
          node {
            id
            parent {
              node {
                id
              }
            }
          }
        }
      }
    }
  }
}
