query StartupConfigQuery($name: String!){
  DcimDevice(name__value: $name) {
    edges {
      node {
        __typename
        name {
          value
        }
        loopback_ip {
          node {
            __typename
            address {
              ip
            }
          }
        }
        interfaces {
          edges {
            node {
              __typename
              name {
                value
              }
              description {
                value
              }
              role {
                value
              }
              status {
                value
              }
              ip_address {
                node {
                  __typename
                  address {
                    value
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
