---
plugin: opsmill.infrahub.inventory
api_endpoint: "http://infrahub-server:8000"
branch: main

timeout: 30
strict: false
hostnames:
  - display_label

nodes:
  DcimDevice:
    include:
      - role
      - mgmt_ip.address
      - pod.parent.name
      - status

compose:
  ansible_host: mgmt_ip.address | regex_replace('/.*$', '')
  infrahub_fabric_name: pod.parent.name
