query FabricPoolCheckQuery($name: String!) {
  NetworkFabric(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        underlay_routing_protocol {
          value
        }
        overlay_routing_protocol {
          value
        }
        fabric_ip_pools {
          edges {
            node {
              __typename
              id
              display_label
              ... on CoreIPPrefixPool {
                name {
                  value
                }
                resources {
                  edges {
                    node {
                      __typename
                      ... on IpamPrefix {
                        prefix {
                          value
                        }
                        role {
                          value
                        }
                      }
                    }
                  }
                }
              }
              ... on CoreIPAddressPool {
                name {
                  value
                }
                resources {
                  edges {
                    node {
                      __typename
                      ... on IpamPrefix {
                        prefix {
                          value
                        }
                        role {
                          value
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  NetworkPod {
    edges {
      node {
        id
        name {
          value
        }
        parent {
          node {
            __typename
              id
              ... on NetworkFabric {
                name {
                  value
                }
                underlay_routing_protocol {
                  value
                }
                fabric_ip_pools {
                edges {
                  node {
                    __typename
                    id
                    display_label
                    ... on CoreIPPrefixPool {
                      name {
                        value
                      }
                      resources {
                        edges {
                          node {
                            __typename
                            ... on IpamPrefix {
                              prefix {
                                value
                              }
                              role {
                                value
                              }
                            }
                          }
                        }
                      }
                    }
                    ... on CoreIPAddressPool {
                      name {
                        value
                      }
                      resources {
                        edges {
                          node {
                            __typename
                            ... on IpamPrefix {
                              prefix {
                                value
                              }
                              role {
                                value
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        pod_ip_pools {
          edges {
            node {
              __typename
              id
              display_label
              ... on CoreIPPrefixPool {
                name {
                  value
                }
                resources {
                  edges {
                    node {
                      __typename
                      ... on IpamPrefix {
                        prefix {
                          value
                        }
                        role {
                          value
                        }
                      }
                    }
                  }
                }
              }
              ... on CoreIPAddressPool {
                name {
                  value
                }
                resources {
                  edges {
                    node {
                      __typename
                      ... on IpamPrefix {
                        prefix {
                          value
                        }
                        role {
                          value
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        racks {
          edges {
            node {
              id
              mlag {
                value
              }
            }
          }
        }
      }
    }
  }
  NetworkLink(role__value: "dci") {
    edges {
      node {
        id
        connected_endpoints {
          edges {
            node {
              __typename
              ... on InterfacePhysical {
                device {
                  node {
                    id
                    ... on DcimDevice {
                      pod {
                        node {
                          parent {
                            node {
                              id
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
